# SPDX-FileCopyrightText: : 2017-2020 The PyPSA-Eur Authors
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: pypsa-eur-docs
channels:
  - conda-forge
  #- bioconda
dependencies:
  #- python
  - pip
  - pypsa>=0.17 
  - atlite=0.0.3

  # Dependencies of the workflow itself
  #- xlrd
  - scikit-learn
  - pycountry
  - seaborn
  #- snakemake-minimal
  - memory_profiler
  - yaml
  - pytables
  - powerplantmatching>=0.4.3

  # Second order dependencies which should really be deps of atlite
  - xarray
  #- netcdf4
  #- bottleneck
  #- toolz
  #- dask
  - progressbar2
  - pyyaml>=5.1.0

  # Include ipython so that one does not inadvertently drop out of the conda
  # environment by calling ipython
  # - ipython

  # GIS dependencies have to come all from conda-forge
  - conda-forge::cartopy
  - conda-forge::fiona
  - conda-forge::proj
  - conda-forge::pyshp
  - conda-forge::geopandas
  - conda-forge::rasterio
  - conda-forge::shapely
  - conda-forge::libgdal

  # The FRESNA/KIT stuff is not packaged for conda yet
  - pip:
    - vresutils==0.3.1
    - https://github.com/FZJ-IEK3-VSA/geokit/archive/v1.2.6.zip
    - https://github.com/FZJ-IEK3-VSA/glaes/archive/v1.1.6.zip
    - cdsapi
    - sphinx
    - sphinx_rtd_theme
